github_data:
  open_issues:
    label: Open Issues
    search: is:open org:wp-cli is:issue sort:created-desc
  open_issues_good_first_issue:
    label: Good First Issues
    search: is:open org:wp-cli is:issue sort:created-desc label:good-first-issue
  open_issues_no_label:
    label: Open Issues Without Label
    search: is:open org:wp-cli is:issue sort:created-desc no:label
  open_pull_requests:
    label: Open Pull Requests
    search: is:open sort:updated-desc org:wp-cli is:pr
  open_pull_requests_awaiting_review:
    label: Open Pull Requests Awaiting Review
    search: is:open sort:updated-desc org:wp-cli is:pr team-review-requested:wp-cli/committers
