github_data:
  open_issues:
    label: Open Issues
    search: is:open org:fp-cli is:issue sort:updated-desc
  open_issues_no_label:
    label: Open Issues Without Label
    search: is:open org:fp-cli is:issue sort:created-desc no:label
  open_issues_label_bug:
    label: Open Bugs
    search: is:open org:fp-cli is:issue sort:created-desc label:bug
  open_issues_good_first_issue:
    label: Good First Issues
    search: is:open org:fp-cli is:issue sort:created-desc label:good-first-issue
  open_pull_requests:
    label: Open Pull Requests
    search: is:open sort:updated-desc org:fp-cli is:pr
  open_pull_requests_awaiting_review:
    label: Open Pull Requests Awaiting Review
    search: is:open sort:updated-desc org:fp-cli is:pr team-review-requested:fp-cli/committers
github_repositories:
  - fp-cli/automated-tests
  - fp-cli/admin-command
  - fp-cli/cache-command
  - fp-cli/checksum-command
  - fp-cli/config-command
  - fp-cli/core-command
  - fp-cli/cron-command
  - fp-cli/db-command
  - fp-cli/dist-archive-command
  - fp-cli/doctor-command
  - fp-cli/embed-command
  - fp-cli/entity-command
  - fp-cli/eval-command
  - fp-cli/export-command
  - fp-cli/extension-command
  - fp-cli/find-command
  - fp-cli/i18n-command
  - fp-cli/import-command
  - fp-cli/language-command
  - fp-cli/maintenance-mode-command
  - fp-cli/media-command
  - fp-cli/package-command
  - fp-cli/php-cli-tools
  - fp-cli/profile-command
  - fp-cli/restful
  - fp-cli/rewrite-command
  - fp-cli/role-command
  - fp-cli/scaffold-command
  - fp-cli/scaffold-package-command
  - fp-cli/search-replace-command
  - fp-cli/server-command
  - fp-cli/shell-command
  - fp-cli/super-admin-command
  - fp-cli/widget-command
  - fp-cli/fp-cli
  - fp-cli/fp-cli-bundle
  - fp-cli/fp-cli-dev
  - fp-cli/fp-cli-tests
  - fp-cli/fp-cli.github.com
  - fp-cli/fp-config-transformer
  - fp-cli/fp-super-cache-cli
