name: Fetch GitHub data

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *' # Run every 5 minutes.

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-github-data:
    name: Fetch GitHub data
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP envirnoment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check existence of composer.json file
        id: check_composer_file
        uses: andstor/file-existence-action@v2
        with:
          files: "composer.json"

      - name: Install Composer dependencies & cache dependencies
        if: steps.check_composer_file.outputs.files_exists == 'true'
        uses: "ramsey/composer-install@v2"
        env:
          COMPOSER_ROOT_VERSION: dev-${{ github.event.repository.default_branch }}

      - name: Configure git user
        run: |
          git config --global user.email "wp-make-coffee@wp-cli.org"
          git config --global user.name "wp-make-coffee"

      - name: Fetch GitHub data
        run: |
          wp dashboard fetch-github-data

      - name: Check if there are changes
        run: echo "CHANGES_DETECTED=$([[ -z $(git status --porcelain) ]] && echo "0" || echo "1")" >> $GITHUB_ENV

      - name: Commit changes
        if: env.CHANGES_DETECTED == 1
        run: |
          git add github-data
          git commit -m "Fetch GitHub data - $(date +'%Y-%m-%d-%H-00')"
          git push origin
